### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by weiweismile** [liyucang-git/liyucang-git.github.io#66]
It's safe to chat here. We are programmers and he doesn't understand these things! He couldn't have seen it.
He is controlling my social interactions, and this desire for control is a bit too strong. I am under a lot of pressure

**Comment by liyucang-git** [comment]
i get

**Comment by weiweismile** [comment]
So what the fuck are you doing? What happened?

**Comment by liyucang-git** [comment]
how can he control your social interactions, aren't he in guangzhou?

**Comment by weiweismile** [comment]
Delete it

**Comment by liyucang-git** [comment]
delete what

**Comment by weiweismile** [comment]
the issue
